#ifndef LIB_H
#define LIB_H

#ifdef THREEDFORCEGENERATOR_EXPORT
#define THREEDFORCEGENERATOR_SYMBOL __declspec(dllexport)
#else // !THREEDFORCEGENERATOR_EXPORT
#ifdef THREEDFORCEGENERATOR_IMPORT
#define THREEDFORCEGENERATOR_SYMBOL __declspec(dllexport)
#else // !THREEDFORCEGENERATOR_IMPORT
#define THREEDFORCEGENERATOR_IMPORT
#endif // THREEDFORCEGENERATOR_IMPORT
#endif // THREEDFORCEGENERATOR_EXPORT

#endif // !LIB_H
